name: Secrets

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Configure Aws Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        Aws_access_key_id: ${{secrets.AWS_acsess_key_id}}
        Aws_secret_access_key: ${{secrets.AWS_secret_access_key}}   
        Aws_region: ${{secrets.Aws_region}}
    - name: List s3 buckets
      run: aws s3api list-buckets
    
